// Code generated by client-gen. DO NOT EDIT.

package agentgateway

import (
	http "net/http"

	v1alpha1agentgateway "github.com/kgateway-dev/kgateway/v2/api/v1alpha1/agentgateway"
	scheme "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type AgentgatewayAgentgatewayInterface interface {
	RESTClient() rest.Interface
	AgentgatewayBackendsGetter
	AgentgatewayParametersGetter
	AgentgatewayPoliciesGetter
}

// AgentgatewayAgentgatewayClient is used to interact with features provided by the agentgateway.dev group.
type AgentgatewayAgentgatewayClient struct {
	restClient rest.Interface
}

func (c *AgentgatewayAgentgatewayClient) AgentgatewayBackends(namespace string) AgentgatewayBackendInterface {
	return newAgentgatewayBackends(c, namespace)
}

func (c *AgentgatewayAgentgatewayClient) AgentgatewayParameters(namespace string) AgentgatewayParametersInterface {
	return newAgentgatewayParameters(c, namespace)
}

func (c *AgentgatewayAgentgatewayClient) AgentgatewayPolicies(namespace string) AgentgatewayPolicyInterface {
	return newAgentgatewayPolicies(c, namespace)
}

// NewForConfig creates a new AgentgatewayAgentgatewayClient for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*AgentgatewayAgentgatewayClient, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new AgentgatewayAgentgatewayClient for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*AgentgatewayAgentgatewayClient, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &AgentgatewayAgentgatewayClient{client}, nil
}

// NewForConfigOrDie creates a new AgentgatewayAgentgatewayClient for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *AgentgatewayAgentgatewayClient {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new AgentgatewayAgentgatewayClient for the given RESTClient.
func New(c rest.Interface) *AgentgatewayAgentgatewayClient {
	return &AgentgatewayAgentgatewayClient{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := v1alpha1agentgateway.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *AgentgatewayAgentgatewayClient) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
