# Image configuration
DOCKER_REGISTRY ?= ghcr.io
DOCKER_REPO ?= agentgateway
IMAGE_NAME ?= agentgateway
VERSION ?= $(shell git describe --tags --always --dirty 2>/dev/null || jj log -r @ -T 'commit_id.shortest(12)' --no-graph 2>/dev/null || echo unknown)
GIT_REVISION ?= $(shell git rev-parse HEAD 2>/dev/null || jj log -r @ -T 'commit_id' --no-graph 2>/dev/null || echo unknown)
IMAGE_TAG ?= $(VERSION)
IMAGE_FULL_NAME ?= $(DOCKER_REGISTRY)/$(DOCKER_REPO)/$(IMAGE_NAME):$(IMAGE_TAG)
DOCKER_BUILDER ?= docker
DOCKER_BUILD_ARGS ?= --build-arg VERSION=$(VERSION) --build-arg GIT_REVISION=$(GIT_REVISION)
export PATH := ./tools:$(PATH)

# docker
.PHONY: docker
docker:
ifeq ($(OS),Windows_NT)
	$(DOCKER_BUILDER) build $(DOCKER_BUILD_ARGS) -f Dockerfile.windows -t $(IMAGE_FULL_NAME) .
else
	$(DOCKER_BUILDER) build $(DOCKER_BUILD_ARGS) -t $(IMAGE_FULL_NAME) . --progress=plain
endif

.PHONY: docker-ci
docker-ci:
ifeq ($(OS),Windows_NT)
	$(DOCKER_BUILDER) build $(DOCKER_BUILD_ARGS) --build-arg PROFILE=ci -f Dockerfile.windows -t $(IMAGE_FULL_NAME) .
else
	$(DOCKER_BUILDER) build $(DOCKER_BUILD_ARGS) --build-arg PROFILE=ci -t $(IMAGE_FULL_NAME) . --progress=plain
endif

.PHONY: docker-musl
docker-musl:
	$(DOCKER_BUILDER) build $(DOCKER_BUILD_ARGS) -t $(IMAGE_FULL_NAME)-musl --build-arg=BUILDER=musl . --progress=plain

CARGO_BUILD_ARGS ?=

# The web UI is embedded into the binary via the `ui` cargo feature, which
# compiles the built assets from ui/out into the binary at build time. Those
# assets are generated by the Node/npm build and are not checked in, so a plain
# `cargo build --features ui` on a fresh checkout fails.
#
# `make build` builds the UI automatically when ui/out is missing. After editing
# UI sources, run `make ui` to rebuild the assets. Set UI=0 to build without the
# embedded UI and skip the Node/npm build, which is useful for fast iteration on
# the proxy itself (no Node toolchain required).
UI ?= 1
ifeq ($(UI),0)
UI_PREREQ :=
UI_FEATURE :=
else
UI_PREREQ := ui/out
UI_FEATURE := --features ui
endif

# ui/out is only built when missing, so build steps that supply their own
# prebuilt assets (the Docker images and release CI both run the UI build first)
# are unaffected. Run `make ui` to force a rebuild after changing UI sources.
ui/out:
	$(MAKE) ui

.PHONY: ui
ui:
	cd ui && npm install && npm run build

# build
.PHONY: build
build: $(UI_PREREQ)
	cargo build --release $(UI_FEATURE) $(CARGO_BUILD_ARGS)
.PHONY: build-target
build-target: $(UI_PREREQ)
	cargo build $(UI_FEATURE) $(CARGO_BUILD_ARGS) --target $(TARGET) --profile $(PROFILE)

# lint
.PHONY: lint
lint:
	cargo fmt --check -- --config imports_granularity=Module,group_imports=StdExternalCrate,normalize_comments=true
	cargo clippy --all-targets

.PHONY: clippy
fix-clippy:
	cargo clippy --fix --allow-staged --allow-dirty --allow-no-vcs

.PHONY: format
format:
	cargo fmt -- --config imports_granularity=Module,group_imports=StdExternalCrate,normalize_comments=true

.PHONY: fix-lint
fix-lint:
	$(MAKE) fix-clippy
	$(MAKE) format

# test
.PHONY: test
test:
	cargo test --all-targets

.PHONY: test-release
test-release:
	cargo test --profile quick-release --all-targets

# clean
.PHONY: clean
clean:
	cargo clean

objects := $(wildcard examples/*/config.json)

.PHONY: check-clean-repo
check-clean-repo:
	@tools/check_clean_repo.sh

.PHONY: gen
gen: generate-apis generate-schema format
	@:

.PHONY: generate-schema
generate-schema:
	@cargo xtask schema

# Code generation for xds apis
.PHONY: generate-apis
generate-apis:
	@PATH="./common/tools:$(PATH)" buf generate --path crates/protos/proto/resource.proto --path crates/protos/proto/ext_mcp.proto

.PHONY: run-validation-deps
run-validation-deps:
	@tools/manage-validation-deps.sh start

.PHONY: stop-validation-deps
stop-validation-deps:
	@tools/manage-validation-deps.sh stop

.PHONY: validate
validate:
	@tools/validate-configs.sh
