# yaml-language-server: $schema=https://agentgateway.dev/schema/config
binds:
- port: 8443
  listeners:
  - name: confidential-vllm
    protocol: HTTPS
    tls:
      cert: /certs/tls.crt
      key: /certs/tls.key
    routes:
    - name: attestation
      matches:
      - path:
          pathPrefix: /attestation
      backends:
      - host: attestation:8081

llm:
  models:
  - name: confidential-vllm
    provider:
      custom:
        model: confidential-vllm
        formats:
        - type: completions
    params:
      model: confidential-vllm
      baseUrl: http://vllm:8000
    defaults:
      temperature: 0
      max_tokens: 128
