{{- $gateway := .Values.agentgateway }}
{{- if eq (($gateway.workload).kind | default "Deployment") "DaemonSet" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "kgateway.gateway.fullname" . }}
  {{- with $gateway.gatewayAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "kgateway.gateway.allLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kgateway.gateway.selectorLabels" . | nindent 6 }}
  template:
    {{- include "kgateway.gateway.podTemplate" . | nindent 4 }}
{{- end }}
