#!/bin/bash

set -e

get-tag () {
  if [[ -n "${TAG:-""}" ]]
  then
    echo ${TAG}
  else
    echo `date +%s`
  fi
}

profile="${1:-dev}"
platform="${2:-}"
tgt="${profile}"
if [[ $tgt == "dev" ]]; then
  tgt=debug
fi

cargo build --profile "${profile}" ${platform:+--target $platform} ${TIMINGS+--timings} || exit 1
if [[ "${DRY_RUN}" == "" ]]; then
  exit 0
fi
tag="$(get-tag)"
dest="localhost:5000/agentgateway:${tag}"

if [[ "$(uname -s)" != "Linux" ]]; then
  # On non-Linux (e.g., Mac), use docker build to produce a linux/amd64 image
  # instead of crane append which would bundle the native (ARM64) binary.
  docker build --platform linux/amd64 --build-arg PROFILE="${profile}" -t "${dest}" .
  docker push "${dest}"
else
  crane mutate --platform linux/amd64 $(
    crane append --platform linux/amd64 \
      -f <(tar -f - -c -s "|./target/${platform:+$platform/}${tgt}/|/usr/bin/|" ./target/${platform:+$platform/}${tgt}/agentgateway) \
      -t ${dest} \
      -b istio/base
  ) --entrypoint /usr/bin/agentgateway -t ${dest} 1>&2
fi
echo ${tag}
echo ${dest} 1>&2
