// Code generated by protoc-gen-jsonshim. DO NOT EDIT.
package api

import (
	bytes "bytes"
	jsonpb "github.com/golang/protobuf/jsonpb"
)

// MarshalJSON is a custom marshaler for McpRequest
func (this *McpRequest) MarshalJSON() ([]byte, error) {
	str, err := ExtMcpMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for McpRequest
func (this *McpRequest) UnmarshalJSON(b []byte) error {
	return ExtMcpUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for McpResponse
func (this *McpResponse) MarshalJSON() ([]byte, error) {
	str, err := ExtMcpMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for McpResponse
func (this *McpResponse) UnmarshalJSON(b []byte) error {
	return ExtMcpUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for McpRequestResult
func (this *McpRequestResult) MarshalJSON() ([]byte, error) {
	str, err := ExtMcpMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for McpRequestResult
func (this *McpRequestResult) UnmarshalJSON(b []byte) error {
	return ExtMcpUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for McpResponseResult
func (this *McpResponseResult) MarshalJSON() ([]byte, error) {
	str, err := ExtMcpMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for McpResponseResult
func (this *McpResponseResult) UnmarshalJSON(b []byte) error {
	return ExtMcpUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for HeaderMutation
func (this *HeaderMutation) MarshalJSON() ([]byte, error) {
	str, err := ExtMcpMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for HeaderMutation
func (this *HeaderMutation) UnmarshalJSON(b []byte) error {
	return ExtMcpUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for McpHeader
func (this *McpHeader) MarshalJSON() ([]byte, error) {
	str, err := ExtMcpMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for McpHeader
func (this *McpHeader) UnmarshalJSON(b []byte) error {
	return ExtMcpUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for Pass
func (this *Pass) MarshalJSON() ([]byte, error) {
	str, err := ExtMcpMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for Pass
func (this *Pass) UnmarshalJSON(b []byte) error {
	return ExtMcpUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

// MarshalJSON is a custom marshaler for AuthorizationError
func (this *AuthorizationError) MarshalJSON() ([]byte, error) {
	str, err := ExtMcpMarshaler.MarshalToString(this)
	return []byte(str), err
}

// UnmarshalJSON is a custom unmarshaler for AuthorizationError
func (this *AuthorizationError) UnmarshalJSON(b []byte) error {
	return ExtMcpUnmarshaler.Unmarshal(bytes.NewReader(b), this)
}

var (
	ExtMcpMarshaler   = &jsonpb.Marshaler{}
	ExtMcpUnmarshaler = &jsonpb.Unmarshaler{AllowUnknownFields: true}
)
